// app/(client)/contact/page.tsx
import { Card } from 'flowbite-react';

export default function Contact() {
  return (
    <main className="flex min-h-screen w-full flex-col items-center p-8">
      <Card className="max-w-sm" imgAlt="Profile picture Jari de Keijzer" imgSrc="/images/blog/image-1.jpg">
        <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          Noteworthy technology acquisitions 2021
        </h5>
        <p className="font-normal text-gray-700 dark:text-gray-400">
          Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.
        </p>
      </Card>
    </main>
  );
}

// pages/contact.vue
<script setup lang="ts">

import {FwbCard, FwbHeading, FwbP} from "flowbite-vue";
</script>

<template>
  <main class="flex min-h-screen w-full flex-col items-center p-8">
    <FwbCard class="max-w-sm" img-alt="Profile picture Jari de Keijzer" img-src="/jari.jpg">
      <div class="p-5">
      <FwbHeading tag="h5" class="text-2xl font-bold tracking-tight text-gray-900">
        Jari de Keijzer
      </FwbHeading>
      <FwbP class="font-normal text-gray-700">
        Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.
      </FwbP>
        </div>
    </FwbCard>
  </main>
</template>

<style scoped>

</style>
